// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "";

// When running without Supabase (e.g. Docker with Go API only), use placeholders
// so the app loads; auth uses the Go backend. Supabase-backed features (workspaces,
// diagrams) will fail until those APIs are migrated or env vars are set.
const url = SUPABASE_URL || "https://placeholder.supabase.co";
const key = SUPABASE_PUBLISHABLE_KEY || "placeholder-anon-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
