openapi: 3.0.3
info:
  title: DWeaver Auth API
  description: Authentication and session endpoints (DWeaver Backend Project Requirements).
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1 base

tags:
  - name: auth
    description: Authentication and session management

paths:
  /auth/register:
    post:
      tags: [auth]
      summary: Register user
      description: User registration with email and password. Returns access and refresh tokens.
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created and tokens returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'

  /auth/login:
    post:
      tags: [auth]
      summary: Login
      description: Authenticate with email and password. Returns access and refresh tokens.
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Tokens returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /auth/logout:
    post:
      tags: [auth]
      summary: Logout
      description: Revoke the given refresh token (session management).
      operationId: logout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '204':
          description: Token revoked
        '400':
          $ref: '#/components/responses/BadRequest'

  /auth/refresh:
    post:
      tags: [auth]
      summary: Refresh JWT
      description: Exchange a valid refresh token for a new access and refresh token pair.
      operationId: refresh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: New tokens returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /auth/forgot-password:
    post:
      tags: [auth]
      summary: Request password reset
      description: Request an email-based password reset. Does not leak whether the email exists.
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '204':
          description: Request accepted (email sent if address exists)
        '400':
          $ref: '#/components/responses/BadRequest'

  /auth/reset-password:
    post:
      tags: [auth]
      summary: Reset password
      description: Set a new password using the token from the reset email.
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '204':
          description: Password updated
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  schemas:
    RegisterRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        password:
          type: string
          minLength: 8
          maxLength: 72
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    LogoutRequest:
      type: object
      required: [refresh_token]
      properties:
        refresh_token:
          type: string
    RefreshRequest:
      type: object
      required: [refresh_token]
      properties:
        refresh_token:
          type: string
    ForgotPasswordRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email
    ResetPasswordRequest:
      type: object
      required: [token, new_password]
      properties:
        token:
          type: string
          description: Token from reset email
        new_password:
          type: string
          minLength: 8
          maxLength: 72

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        email_verified:
          type: boolean
        created_at:
          type: string
          format: date-time

    RegisterResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/UserResponse'
            access_token:
              type: string
            refresh_token:
              type: string
            expires_in:
              type: integer
              description: Access token TTL in seconds
    LoginResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/UserResponse'
            access_token:
              type: string
            refresh_token:
              type: string
            expires_in:
              type: integer
    RefreshResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            access_token:
              type: string
            refresh_token:
              type: string
            expires_in:
              type: integer

    ErrorBody:
      type: object
      properties:
        code:
          type: string
          example: invalid_input
        message:
          type: string
        details:
          type: object
          additionalProperties: true

  responses:
    BadRequest:
      description: Invalid or missing input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
          example:
            code: invalid_input
            message: Invalid or missing input.
    Unauthorized:
      description: Invalid credentials or expired token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
          example:
            code: unauthorized
            message: Invalid email or password.
    Conflict:
      description: Email already registered
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
          example:
            code: conflict
            message: An account with this email already exists.
