openapi: 3.0.3
info:
  title: DWeaver Workspace API
  description: Workspace and invitation endpoints (DWeaver Backend Project Requirements).
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1 base

tags:
  - name: workspaces
    description: Workspace CRUD and settings
  - name: members
    description: Workspace member management
  - name: invitations
    description: Invitations and accept

security:
  - BearerAuth: []

paths:
  /workspaces:
    get:
      tags: [workspaces]
      summary: List workspaces
      description: Returns workspaces where the current user is a member. Each item includes the current user's role (owner, admin, member, viewer).
      operationId: listWorkspaces
      responses:
        '200':
          description: List of workspaces
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      tags: [workspaces]
      summary: Create workspace
      description: Creates a workspace and adds the current user as owner.
      operationId: createWorkspace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkspaceRequest'
      responses:
        '201':
          description: Workspace created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /workspaces/{id}:
    get:
      tags: [workspaces]
      summary: Get workspace
      description: Returns workspace details if the current user is a member.
      operationId: getWorkspace
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      responses:
        '200':
          description: Workspace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceDataResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags: [workspaces]
      summary: Update workspace
      description: Updates workspace (owner or admin only).
      operationId: updateWorkspace
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkspaceRequest'
      responses:
        '200':
          description: Workspace updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [workspaces]
      summary: Delete workspace
      description: Deletes the workspace (owner only).
      operationId: deleteWorkspace
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      responses:
        '204':
          description: Workspace deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /workspaces/{id}/members:
    get:
      tags: [members]
      summary: List members
      description: Returns members of the workspace.
      operationId: listMembers
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      responses:
        '200':
          description: List of members
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /workspaces/{id}/members/{userId}:
    put:
      tags: [members]
      summary: Update member role
      description: Updates a member's role (owner or admin only).
      operationId: updateMemberRole
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMemberRoleRequest'
      responses:
        '200':
          description: Member updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [members]
      summary: Remove member
      description: Removes a member from the workspace (owner or admin only).
      operationId: removeMember
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Member removed
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /workspaces/{id}/invitations:
    post:
      tags: [invitations]
      summary: Invite member
      description: Creates an invitation for the given email (owner or admin only). 7-day expiry.
      operationId: inviteMember
      parameters:
        - $ref: '#/components/parameters/WorkspaceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteMemberRequest'
      responses:
        '201':
          description: Invitation created (token in response for link)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'

  /invitations/accept:
    post:
      tags: [invitations]
      summary: Accept invitation
      description: Joins the workspace using the invitation token.
      operationId: acceptInvitation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptInvitationRequest'
      responses:
        '200':
          description: Joined workspace (returns workspace)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    WorkspaceId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    CreateWorkspaceRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 4096
        color:
          type: string
          maxLength: 20
        tags:
          type: array
          items:
            type: string
    UpdateWorkspaceRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 4096
        color:
          type: string
          maxLength: 20
        tags:
          type: array
          items:
            type: string
    InviteMemberRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        role:
          type: string
          enum: [admin, member, viewer]
    UpdateMemberRoleRequest:
      type: object
      required: [role]
      properties:
        role:
          type: string
          enum: [owner, admin, member, viewer]
    AcceptInvitationRequest:
      type: object
      required: [token]
      properties:
        token:
          type: string
          format: uuid
    WorkspaceResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        color:
          type: string
        tags:
          type: array
          items:
            type: string
        created_by:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    MemberResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        workspace_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        role:
          type: string
          enum: [owner, admin, member, viewer]
        invited_by:
          type: string
          format: uuid
        joined_at:
          type: string
          format: date-time
    InvitationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        workspace_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          type: string
        token:
          type: string
          format: uuid
        invited_by:
          type: string
          format: uuid
        expires_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
    WorkspaceWithRoleResponse:
      description: Workspace plus the current user's role (used in list response).
      allOf:
        - $ref: '#/components/schemas/WorkspaceResponse'
        - type: object
          required: [role]
          properties:
            role:
              type: string
              enum: [owner, admin, member, viewer]
    WorkspaceListResponse:
      type: object
      description: GET /workspaces returns { "data": [ WorkspaceWithRoleResponse, ... ] }.
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceWithRoleResponse'
    WorkspaceDataResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/WorkspaceResponse'
    MemberListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/MemberResponse'
    MemberDataResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/MemberResponse'
    InvitationDataResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/InvitationResponse'
    ErrorBody:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
  responses:
    BadRequest:
      description: Invalid or missing input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
    Unauthorized:
      description: Missing or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
    Forbidden:
      description: Not allowed (e.g. not a member, or not owner/admin)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
    Conflict:
      description: Conflict (e.g. invitation already exists)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
